"""empty message

Revision ID: 14f9fb7d04f5
Revises: b43b57b19cd8
Create Date: 2018-10-15 01:50:03.877818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f9fb7d04f5'
down_revision = 'b43b57b19cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_delete')
    # ### end Alembic commands ###
