"""empty message

Revision ID: 7ac1f8bf1c94
Revises: 14f9fb7d04f5
Create Date: 2018-10-15 01:50:43.232414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ac1f8bf1c94'
down_revision = '14f9fb7d04f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
